#!/usr/bin/env bash
# test/build_test_map.sh — build the type-grid test map.
#
# Renders test/area_type_grid.osm (a synthetic grid of polygon/line/point
# types, generated by gen_grid_osm.py) with test/test_style, so style/TYP
# changes can be eyeballed on device without a full map build.
#
# Output lands in build/layers/ as a single .img tile.
#
# Usage: test/build_test_map.sh

TEST_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
source "$TEST_DIR/../lib/common.sh"

# This harness uses its own style directory and series name.
STYLE_DIR="$TEST_DIR"
STYLE=test_style
SERIES_NAME=sl-test

GRID_OSM="$TEST_DIR/area_type_grid.osm"
MAPNAME=53130099

need_file "$TEST_DIR/test_style/options"
if [ ! -f "$GRID_OSM" ]; then
    log "Extracting area_type_grid.osm from zip"
    need_cmd unzip
    unzip -o "$TEST_DIR/area_type_grid.osm.zip" -d "$TEST_DIR"
fi

mkdir -p "$LAYERS_DIR"
log "Building type-grid test map"
run_mkgmap "$PROJECT_ROOT/arg/test.args" "$MAPNAME" "$GRID_OSM"
log "Done. Test tile(s):"
ls -lh "$LAYERS_DIR"/*.img
