#!/usr/bin/env bash
# db.sh — run PostgreSQL/PostGIS and pgAdmin in podman, for the cleanse stage.
#
# Usage: ./db.sh [start|stop|status|rm|purge]
#
#   start   create the pod + containers and start them (default; idempotent)
#   stop    stop the pod (containers and data volume are kept)
#   status  show pod/container status
#   rm      stop and remove the pod and containers (data volume is kept)
#   purge   rm + delete the PostgreSQL data volume (ALL DB DATA IS LOST)
#
# PostgreSQL is exposed on localhost:$PG_PORT with the role from
# config/build.conf (PG_USER, default osm_build) as superuser, using trust
# auth — no password needed from localhost, which is what psql and osmosis
# (cleanse_data.sh) expect. pgAdmin is at http://localhost:$PGADMIN_PORT;
# add a server there with host 127.0.0.1 (the containers share a pod).
#
# Requires podman to be installed and configured.

source "$(dirname "$(readlink -f "$0")")/lib/common.sh"

POD_NAME=${POD_NAME:-sl-to-garmin-db}
PG_CONTAINER="$POD_NAME-postgres"
PGADMIN_CONTAINER="$POD_NAME-pgadmin"
PG_VOLUME=${PG_VOLUME:-sl-to-garmin-pgdata}

PG_IMAGE=${PG_IMAGE:-docker.io/postgis/postgis:16-3.4}
# PostgreSQL's dynamic shared memory lives in /dev/shm, which defaults to
# 64 MiB in containers — too small for the osmosis import (causes "could not
# resize shared memory segment ... No space left on device"). Because the
# containers share the pod's IPC namespace, this must be set on the POD
# (its infra container owns /dev/shm), not on the postgres container.
PG_SHM_SIZE=${PG_SHM_SIZE:-2g}
PGADMIN_IMAGE=${PGADMIN_IMAGE:-docker.io/dpage/pgadmin4:latest}
PGADMIN_PORT=${PGADMIN_PORT:-8080}
# Note: pgAdmin validates this address and rejects reserved TLDs (.local etc.)
PGADMIN_EMAIL=${PGADMIN_EMAIL:-admin@sl-to-garmin.com}
PGADMIN_PASSWORD=${PGADMIN_PASSWORD:-admin}
# pgAdmin pre-registration file, generated by start() and mounted into the
# pgAdmin container (read on pgAdmin startup).
PGADMIN_SERVERS_JSON="$BUILD_DIR/pgadmin-servers.json"

# write_pgadmin_servers_json — pre-register the pod's PostgreSQL server in
# pgAdmin (host 127.0.0.1:5432 inside the pod's shared network; trust auth,
# so no password is stored).
write_pgadmin_servers_json() {
    mkdir -p "$BUILD_DIR"
    cat > "$PGADMIN_SERVERS_JSON" <<EOF
{
  "Servers": {
    "1": {
      "Name": "PostgreSQL ($POD_NAME)",
      "Group": "Servers",
      "Host": "127.0.0.1",
      "Port": 5432,
      "MaintenanceDB": "postgres",
      "Username": "$PG_USER",
      "SSLMode": "disable",
      "Comment": "Auto-registered by db.sh"
    }
  }
}
EOF
}

# run_or_start <container-name> <run-args...> — create the container if
# missing, start it if it exists but is stopped.
run_or_start() {
    local name="$1"
    shift
    if ! podman container exists "$name"; then
        podman run -d --pod "$POD_NAME" --name "$name" "$@"
    elif [ "$(podman inspect -f '{{.State.Status}}' "$name")" != running ]; then
        log "Starting existing container $name"
        podman start "$name"
    fi
}

start() {
    need_cmd podman
    if ! podman pod exists "$POD_NAME"; then
        log "Creating pod $POD_NAME (ports $PG_PORT -> postgres, $PGADMIN_PORT -> pgAdmin)"
        podman pod create --name "$POD_NAME" \
            --shm-size="$PG_SHM_SIZE" \
            -p "$PG_PORT:5432" -p "$PGADMIN_PORT:80"
    fi
    if ! podman container exists "$PG_CONTAINER"; then
        log "Starting PostgreSQL/PostGIS container ($PG_IMAGE)"
    fi
    run_or_start "$PG_CONTAINER" \
        -v "$PG_VOLUME:/var/lib/postgresql/data" \
        -e POSTGRES_USER="$PG_USER" \
        -e POSTGRES_HOST_AUTH_METHOD=trust \
        "$PG_IMAGE"
    if ! podman container exists "$PGADMIN_CONTAINER"; then
        log "Starting pgAdmin container ($PGADMIN_IMAGE)"
        write_pgadmin_servers_json
    fi
    run_or_start "$PGADMIN_CONTAINER" \
        -e PGADMIN_DEFAULT_EMAIL="$PGADMIN_EMAIL" \
        -e PGADMIN_DEFAULT_PASSWORD="$PGADMIN_PASSWORD" \
        -v "$PGADMIN_SERVERS_JSON:/pgadmin4/servers.json:ro" \
        "$PGADMIN_IMAGE"
    log "Waiting for PostgreSQL to accept connections"
    local tries=0
    until podman exec "$PG_CONTAINER" pg_isready -U "$PG_USER" -q; do
        tries=$((tries + 1))
        [ $tries -gt 30 ] && die "PostgreSQL did not become ready in time"
        sleep 1
    done
    status
    cat <<EOF

PostgreSQL/PostGIS : localhost:$PG_PORT  role '$PG_USER' (trust auth, no password)
pgAdmin            : http://localhost:$PGADMIN_PORT  ($PGADMIN_EMAIL / $PGADMIN_PASSWORD)
                     -> server 'PostgreSQL ($POD_NAME)' is pre-registered

The cleanse stage works out of the box now:
    ./build_map.sh --pg-cleanse
EOF
}

stop() {
    need_cmd podman
    log "Stopping pod $POD_NAME"
    podman pod stop "$POD_NAME"
}

status() {
    need_cmd podman
    podman pod ps --filter name="$POD_NAME"
    podman ps -a --filter pod="$POD_NAME" \
        --format 'table {{.Names}}\t{{.Status}}\t{{.Image}}'
}

remove() {
    need_cmd podman
    log "Removing pod $POD_NAME and its containers (data volume kept)"
    podman pod rm -f "$POD_NAME"
}

purge() {
    remove
    log "Deleting PostgreSQL data volume $PG_VOLUME"
    podman volume rm -f "$PG_VOLUME"
}

case "${1:-start}" in
    start)        start ;;
    stop)         stop ;;
    status)       status ;;
    rm)           remove ;;
    purge)        purge ;;
    -h|--help)    sed -n '2,20p' "$0" ;;
    *)            die "unknown command: $1 (start|stop|status|rm|purge)" ;;
esac
